// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5458iFYpX_GwtZ9rPNp2wELaW3orxfw',
    appId: '1:764443138768:web:784bd178f121711a255cd5',
    messagingSenderId: '764443138768',
    projectId: 'mini-98b04',
    authDomain: 'mini-98b04.firebaseapp.com',
    storageBucket: 'mini-98b04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOPOTXtKYtggpijizW-XNNo928Q_e8qPA',
    appId: '1:764443138768:android:384ceb9c9d8abae2255cd5',
    messagingSenderId: '764443138768',
    projectId: 'mini-98b04',
    storageBucket: 'mini-98b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1Tgrs3QObRe8yqDkyl1jULI97gDWqtU',
    appId: '1:764443138768:ios:587adfdb9debf40f255cd5',
    messagingSenderId: '764443138768',
    projectId: 'mini-98b04',
    storageBucket: 'mini-98b04.firebasestorage.app',
    iosBundleId: 'com.example.chpsmamacareMain01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD1Tgrs3QObRe8yqDkyl1jULI97gDWqtU',
    appId: '1:764443138768:ios:587adfdb9debf40f255cd5',
    messagingSenderId: '764443138768',
    projectId: 'mini-98b04',
    storageBucket: 'mini-98b04.firebasestorage.app',
    iosBundleId: 'com.example.chpsmamacareMain01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm5458iFYpX_GwtZ9rPNp2wELaW3orxfw',
    appId: '1:764443138768:web:4ed6058b740d82f0255cd5',
    messagingSenderId: '764443138768',
    projectId: 'mini-98b04',
    authDomain: 'mini-98b04.firebaseapp.com',
    storageBucket: 'mini-98b04.firebasestorage.app',
  );

}