// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1Ah5N9HksLDqCbq0XzIGSNhNHiIb4UY',
    appId: '1:402480661551:web:6453a1fa8ce0dc919cf2da',
    messagingSenderId: '402480661551',
    projectId: 'mini33-69a7c',
    authDomain: 'mini33-69a7c.firebaseapp.com',
    storageBucket: 'mini33-69a7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYmhWTqTP42YaS_0vh4ySfsPjDKwX05Hw',
    appId: '1:402480661551:android:f1a70edadb5891c59cf2da',
    messagingSenderId: '402480661551',
    projectId: 'mini33-69a7c',
    storageBucket: 'mini33-69a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG0bYd076seq_GbJ0LcYbNUQailaD0NQg',
    appId: '1:402480661551:ios:8a88ff840f685b7a9cf2da',
    messagingSenderId: '402480661551',
    projectId: 'mini33-69a7c',
    storageBucket: 'mini33-69a7c.firebasestorage.app',
    iosBundleId: 'com.example.chpsmamacareMain01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG0bYd076seq_GbJ0LcYbNUQailaD0NQg',
    appId: '1:402480661551:ios:8a88ff840f685b7a9cf2da',
    messagingSenderId: '402480661551',
    projectId: 'mini33-69a7c',
    storageBucket: 'mini33-69a7c.firebasestorage.app',
    iosBundleId: 'com.example.chpsmamacareMain01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV1Ah5N9HksLDqCbq0XzIGSNhNHiIb4UY',
    appId: '1:402480661551:web:f289081f93e4e2499cf2da',
    messagingSenderId: '402480661551',
    projectId: 'mini33-69a7c',
    authDomain: 'mini33-69a7c.firebaseapp.com',
    storageBucket: 'mini33-69a7c.firebasestorage.app',
  );

}